name: Build and deploy Python project to Azure Function App - api-generator-mental-boom

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Your function app root
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into .python_packages
        run: |
          python -m pip install --upgrade pip
          pip install -t .python_packages/lib/site-packages -r requirements.txt

      - name: Zip artifact for deployment (including dependencies)
        run: |
          zip -r release.zip . -x "venv/*" -x ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions (via Azure CLI)
        run: |
          az functionapp deployment source config-zip \
            --name api-generator-mental-boom \
            --resource-group <your-resource-group-name> \
            --src release.zip
